apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: auto-scalling-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: auto-scalling-app
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Initial, Auto
